FLOAT_SIZE = 4

PIECE_COUNT = 6
COLOR_COUNT = 2
COLOR_PIECE_COUNT = PIECE_COUNT * COLOR_COUNT
FILE_COUNT = 8
RANK_COUNT = 8
SQUARE_COUNT = FILE_COUNT * RANK_COUNT

MAX_VALUE = 128
INPUT_NEURONS = COLOR_PIECE_COUNT * SQUARE_COUNT
HIDDEN_NEURONS = 256
OUTPUT_NEURONS = 1

SCORE_MULTIPLIER = 600.0
